[build]
target = "wasm32-wasip1-threads"
rustflags = [
    "--cfg",
    "tokio_unstable",
    "-Ctarget-feature=-crt-static",
    "-L/opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasip1-threads",
    # wasm-ld --initial-memory 20MB
    "-Clink-arg=--initial-memory=20971520",
    # wasm-ld --max-memory 1G
    "-Clink-arg=--max-memory=1073741824",
    # pass -g to clang, not to wasm-ld
    # "--remap-path-prefix",
    # "src/=/wasm/debug",
    # "-Clink-arg=-gsplit-dwarf",
    # "-Clink-arg=-gdwarf-5",
]

[target.wasm32-wasip1-threads]
linker = "/opt/wasi-sdk/bin/wasm-ld"
ar = "/opt/wasi-sdk/bin/llvm-ar"

[env]
CLANGCC = "/opt/wasi-sdk/bin/clang"
CLANGCXX = "/opt/wasi-sdk/bin/clang++"
CC = "/opt/wasi-sdk/bin/clang"
CXX = "/opt/wasi-sdk/bin/clang++"
WASI_SDK_PATH = "/opt/wasi-sdk"
CLANG_PATH = "/opt/wasi-sdk/bin/clang"
